import XCTest
@testable import PagerCore

final class AppearancePrefsTests: XCTestCase {
    /// A pre-change saved link, hand-written (NOT generated by encoding a
    /// current struct): has `colorHex`, lacks `screenColor`/`caseColor`. If
    /// decode throws on this, `LinkStore` wipes the user's real links.
    func testLegacyAppearancePrefsDecodesWithDefaults() throws {
        let json = """
        {"maxWidth":250,"fontSize":13,"colorHex":"#FF0000","opacity":0.8}
        """
        let prefs = try JSONDecoder().decode(AppearancePrefs.self, from: Data(json.utf8))
        XCTAssertEqual(prefs.maxWidth, 250)
        XCTAssertEqual(prefs.fontSize, 13)
        XCTAssertEqual(prefs.opacity, 0.8)
        XCTAssertEqual(prefs.screenColor, .green)
        XCTAssertEqual(prefs.caseColor, .darkGrey)
    }

    func testPagerLinkDecodesWithoutWindowFrame() throws {
        let json = """
        {"id":"\(UUID().uuidString)","code":"ABCDEFGHJKMNPQRS","nickname":"n",
         "appearance":{"maxWidth":250,"fontSize":13,"opacity":1},
         "cachedText":"hi","cachedWrittenAt":7}
        """
        let link = try JSONDecoder().decode(PagerLink.self, from: Data(json.utf8))
        XCTAssertNil(link.windowFrame)
    }

    /// `yellow` was removed from `ScreenColor`; prefs saved while it existed
    /// must decode to orange (its nearest hue), not throw — a throw here
    /// would wipe the user's links. Unknown future values fall back to green.
    func testRemovedYellowScreenColorDecodesToOrange() throws {
        let json = """
        {"maxWidth":250,"fontSize":13,"opacity":1,"screenColor":"yellow","caseColor":"beige"}
        """
        let prefs = try JSONDecoder().decode(AppearancePrefs.self, from: Data(json.utf8))
        XCTAssertEqual(prefs.screenColor, .orange)
        XCTAssertEqual(prefs.caseColor, .beige)

        let unknown = """
        {"maxWidth":250,"fontSize":13,"opacity":1,"screenColor":"chartreuse"}
        """
        XCTAssertEqual(try JSONDecoder().decode(AppearancePrefs.self, from: Data(unknown.utf8)).screenColor,
                       .green)
    }

    func testAppearancePrefsNewFieldsRoundTrip() throws {
        var prefs = AppearancePrefs()
        prefs.screenColor = .pink
        prefs.caseColor = .beige
        let data = try JSONEncoder().encode(prefs)
        let decoded = try JSONDecoder().decode(AppearancePrefs.self, from: data)
        XCTAssertEqual(decoded.screenColor, .pink)
        XCTAssertEqual(decoded.caseColor, .beige)
    }

    func testPagerLinkWindowFrameRoundTrip() throws {
        var link = PagerLink(code: ShareCode.generate().full, nickname: "n")
        link.windowFrame = CGRect(x: 1, y: 2, width: 3, height: 4)
        let data = try JSONEncoder().encode(link)
        let decoded = try JSONDecoder().decode(PagerLink.self, from: data)
        XCTAssertEqual(decoded.windowFrame, CGRect(x: 1, y: 2, width: 3, height: 4))
    }
}
